package constant

const (
	ELEMENT_TYPE_FIRE  = 1
	ELEMENT_TYPE_WATER = 2
	ELEMENT_TYPE_GRASS = 3
	ELEMENT_TYPE_ELEC  = 4
	ELEMENT_TYPE_ICE   = 5
	ELEMENT_TYPE_WIND  = 7
	ELEMENT_TYPE_ROCK  = 8
)

type FightPropEnergy struct {
	CurEnergy int
	MaxEnergy int
}

var ELEMENT_TYPE_FIGHT_PROP_ENERGY_MAP map[int]*FightPropEnergy

func init() {
	ELEMENT_TYPE_FIGHT_PROP_ENERGY_MAP = make(map[int]*FightPropEnergy)
	ELEMENT_TYPE_FIGHT_PROP_ENERGY_MAP[ELEMENT_TYPE_FIRE] = &FightPropEnergy{
		CurEnergy: FIGHT_PROP_CUR_FIRE_ENERGY,
		MaxEnergy: FIGHT_PROP_MAX_FIRE_ENERGY,
	}
	ELEMENT_TYPE_FIGHT_PROP_ENERGY_MAP[ELEMENT_TYPE_WATER] = &FightPropEnergy{
		CurEnergy: FIGHT_PROP_CUR_WATER_ENERGY,
		MaxEnergy: FIGHT_PROP_MAX_WATER_ENERGY,
	}
	ELEMENT_TYPE_FIGHT_PROP_ENERGY_MAP[ELEMENT_TYPE_GRASS] = &FightPropEnergy{
		CurEnergy: FIGHT_PROP_CUR_GRASS_ENERGY,
		MaxEnergy: FIGHT_PROP_MAX_GRASS_ENERGY,
	}
	ELEMENT_TYPE_FIGHT_PROP_ENERGY_MAP[ELEMENT_TYPE_ELEC] = &FightPropEnergy{
		CurEnergy: FIGHT_PROP_CUR_ELEC_ENERGY,
		MaxEnergy: FIGHT_PROP_MAX_ELEC_ENERGY,
	}
	ELEMENT_TYPE_FIGHT_PROP_ENERGY_MAP[ELEMENT_TYPE_ICE] = &FightPropEnergy{
		CurEnergy: FIGHT_PROP_CUR_ICE_ENERGY,
		MaxEnergy: FIGHT_PROP_MAX_ICE_ENERGY,
	}
	ELEMENT_TYPE_FIGHT_PROP_ENERGY_MAP[ELEMENT_TYPE_WIND] = &FightPropEnergy{
		CurEnergy: FIGHT_PROP_CUR_WIND_ENERGY,
		MaxEnergy: FIGHT_PROP_MAX_WIND_ENERGY,
	}
	ELEMENT_TYPE_FIGHT_PROP_ENERGY_MAP[ELEMENT_TYPE_ROCK] = &FightPropEnergy{
		CurEnergy: FIGHT_PROP_CUR_ROCK_ENERGY,
		MaxEnergy: FIGHT_PROP_MAX_ROCK_ENERGY,
	}
}
